enyo.depends(
	"Spinn/RssToJson.js",
	"Spinn/EnyoExtensions/depends.js",
	"Spinn/PhoneExtensions/depends.js",
	"Spinn/Animator/depends.js",
	"Spinn/CountPill/depends.js",
	"Spinn/ActivityToolButton/depends.js",
	"Spinn/AffirmDeny/depends.js",
	"Spinn/CountableItem/depends.js",
	"Spinn/IconItem/depends.js",
	"Spinn/ConfirmationDialog/depends.js",
	"Spinn/InfoDialog/depends.js",
	"Spinn/InputDialog/depends.js",
	"Spinn/AboutDialog/depends.js",
	"Spinn/SelectableVirtualList/depends.js",
	"Spinn/SelectableVirtualRepeater/depends.js"
);