enyo.depends(
	"Spinn/javascripts/Utils.js",
	"Spinn/PhoneUtils/depends.js",
	"Spinn/javascripts/RssToJson.js",
	"Spinn/javascripts/WorkQueue.js",
	"Spinn/javascripts/DataModel.js",
	"Spinn/Animator/depends.js",
	"Spinn/CountPill/depends.js",
	"Spinn/ActivityToolButton/depends.js",
	"Spinn/AffirmDeny/depends.js",
	"Spinn/IconLabel/depends.js",
	"Spinn/CountableIconItem/depends.js",
	"Spinn/ConfirmationDialog/depends.js",
	"Spinn/InfoDialog/depends.js",
	"Spinn/InputDialog/depends.js",
	"Spinn/AboutDialog/depends.js",
	"Spinn/SelectableVirtualList/depends.js",
	"Spinn/SelectableVirtualRepeater/depends.js"
);